Feature/biometric type
paychex/cordova-plugin-keychain-touch-id pull request #1
Opened 2017-10-30 14:36 UTC by lloydmurray

Added biometricType method to assist users in providing the correct verbiage for FaceId/TouchId devices.

2017-10-30 15:18 UTC, dbarnespaychex requested changes

2017-10-30 15:18 UTC, dbarnespaychex commented on readme.md
> +currently implemented for ios.  android api currently returns NONE.
sorry i didn't see this before, but the android API now returns NONE or TOUCH, correct?

2017-10-30 15:18 UTC, dbarnespaychex commented on src/android/FingerprintAuth.java
> +            JSONObject resultJson = new JSONObject();
am i blind, or is resultJson never used?

2017-10-30 15:29 UTC, dbarnespaychex approved these changes

2017-10-31 12:32 UTC, merged

2017-10-31 18:17 UTC, skammerd commented
I understand the code, and it looks good as far as the content. I am a little bit leary of the fact that the IOS files are touched.[h,m,js], and they have FACIAL recognition stuff in them. I know the source isn't ours, and that you would have liked to call it biometric[h,m,js], as this is a little misleading in naming convention. Short of having the Author restructure the code though (A breaking change), I do not see an alternative.